@baseUrl = http://localhost:5209

### Get Answer to Question
# Retrieves an answer to a user's question
GET {{baseUrl}}/api/question?query=Hello
Accept: application/json

###

### Get Answer to Another Question
GET {{baseUrl}}/api/question?query=What is your name?
Accept: application/json 

###

### Get Weather Forecast
# Retrieves a 5-day weather forecast
GET {{baseUrl}}/weatherforecast
Accept: application/json

###
