@baseUrl = http://localhost:5209

### OpenAPI JSON Definition
# Access the API specification
GET {{baseUrl}}/openapi/v1.json
Accept: application/json

###

### OpenAPI UI (Development Only)
# Access the interactive API documentation
GET {{baseUrl}}/openapi/ui
Accept: text/html

###

### Example API Endpoints (For Future Implementation)

### Get Resource by ID
GET {{baseUrl}}/api/resources/{{$guid}}
Accept: application/json

###

### Create New Resource
POST {{baseUrl}}/api/resources
Content-Type: application/json

{
  "name": "Example Resource",
  "description": "This is an example resource",
  "createdAt": "{{$timestamp}}",
  "attributes": {
    "key1": "value1",
    "key2": 123
  }
}

###

### Update Resource
PUT {{baseUrl}}/api/resources/{{$guid}}
Content-Type: application/json

{
  "name": "Updated Resource",
  "description": "This resource has been updated",
  "attributes": {
    "key1": "new value",
    "key2": 456
  }
}

###

### Delete Resource
DELETE {{baseUrl}}/api/resources/{{$guid}}

###

### Save Response Example
# This will save the response to a file
GET {{baseUrl}}/api/question?query=hello
Accept: application/json

> ./response-example.json 
