// HTTP request file for Clarus Mens API
// =====================================

// This file is used to test the API using the HTTP client.

@ClarusMensAPI_HostAddress = http://localhost:5209

### OpenAPI JSON Definition
# Access the API specification
GET {{ClarusMensAPI_HostAddress}}/openapi/v1.json
Accept: application/json

### OpenAPI UI (Swagger)
# Access the interactive API documentation
GET {{ClarusMensAPI_HostAddress}}/swagger
Accept: text/html

### Version information
# Get the version information
GET {{ClarusMensAPI_HostAddress}}/api/version
Accept: application/json

### Question
# Get the answer
GET {{ClarusMensAPI_HostAddress}}/api/question?query=hello
Accept: application/json
