@ClarusMensAPI_HostAddress = http://localhost:5209

### OpenAPI JSON Definition
# Access the API specification
GET {{ClarusMensAPI_HostAddress}}/openapi/v1.json
Accept: application/json

###

### OpenAPI UI (Development Only)
# Access the interactive API documentation
GET {{ClarusMensAPI_HostAddress}}/openapi/ui
Accept: text/html

###

GET {{ClarusMensAPI_HostAddress}}/api/question?query=hello
Accept: application/json

###
