# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Unit Tests
      run: dotnet build -c Testing --no-restore -o _testbuild/tests/ClarusMensAPI.UnitTests
      working-directory: tests/ClarusMensAPI.UnitTests
    - name: Build Integration Tests
      run: dotnet build -c Testing --no-restore -o _testbuild/tests/ClarusMensAPI.IntegrationTests
      working-directory: tests/ClarusMensAPI.IntegrationTests
    - name: Build Functional Tests
      run: dotnet build -c Testing --no-restore -o _testbuild/tests/ClarusMensAPI.FunctionalTests
      working-directory: tests/ClarusMensAPI.FunctionalTests
    - name: Test
      run: dotnet test -c Testing --no-build --verbosity normal --test-adapter-path:_testbuild
